swipe:
  4:
    left:
      command: "playerctl --player=spotify,vlc previous" # History forward
    right:
      command: "playerctl --player=spotify,vlc next" # History forward
    up:
      command: "xdotool key super" # Activity
    down:
      command: "xdotool key super" # Activity
  3:
    left:
      command: "hyprctl dispatch workspace +1" # Switch to next workspace
    right:
      command: "hyprctl dispatch workspace -1" # Switch to next workspace
    up:
      command: "hyprctl dispatch togglespecialworkspace magic" # Switch to next workspace
    down:
      command: "xdotool key ctrl+alt+Up" # Switch to previous workspace
pinch:
  in:
    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
  out:
    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
hold:
  4:
      command: "playerctl --player=spotify,vlc play-pause" # History forward


threshold:
  hold: 0
